// import React from 'react';

export const products = [
	{
		id: 1,
		period: 1,
		group: 1,
		symbol: 'H',
		name: 'Водород',
		latname: 'Hydrogenium',
		aem: 1.00794,
		density: 0.08988,
		melting: -259.1,
		boiling: -252.9,
		opening: 1766,
		discoverer: 'Кавендиш',
		families: '#a0ffa0',
		focus: false,
		img:
			'https://upload.wikimedia.org/wikipedia/commons/8/83/Hydrogen_discharge_tube.jpg',
	},
	{
		id: 2,
		period: 1,
		group: 18,
		symbol: 'He',
		name: 'Гелий',
		latname: 'Helium',
		aem: 4.002602,
		density: 0.17,
		melting: -272.2,
		boiling: -268.9,
		opening: 1895,
		discoverer: 'Локьер, Жансен (в спектре Солнца), Рамзай (на Земле)',
		families: '#c0ffff',
		focus: false,
		img:
			'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Helium_amp.jpg/150px-Helium_amp.jpg',
	},
	{
		id: 3,
		period: 2,
		group: 1,
		symbol: 'Li',
		name: 'Литий',
		latname: 'Lithium',
		aem: 6.941,
		density: 0.53,
		melting: 180.5,
		boiling: 1317,
		opening: 1817,
		discoverer: 'Арфведсон',
		families: '#f66',
		focus: false,
		img:
			'https://www.planetarium-moscow.ru/upload/medialibrary/db4/db44bc13bbf21a70bd296a5c3b9b1a23.png',
	},
	{
		id: 4,
		period: 2,
		group: 2,
		symbol: 'Be',
		name: 'Бериллий',
		latname: 'Beryllium',
		aem: 9.012182,
		density: 1.85,
		melting: 1278,
		boiling: 2970,
		opening: 1797,
		discoverer: 'Воклен',
		families: '#ffdead',
		focus: false,
		img:
			'https://avatars.mds.yandex.net/get-zen_doc/96506/pub_5b4f82709b38ef00a9d97c06_5b5092d29b38ef00a9d9873d/scale_1200',
	},
	{
		id: 5,
		period: '2',
		group: '13',
		symbol: 'B',
		name: 'Бор',
		latname: 'Borum',
		aem: '10,811',
		density: '2,46',
		melting: '2300',
		boiling: '2550',
		opening: '1808',
		discoverer: 'Дэви и Гей-Люссак',
		families: '#cc9',
		focus: false,
	},
	{
		id: 6,
		period: '2',
		group: '14',
		symbol: 'C',
		name: 'Углерод',
		latname: 'Carboneum',
		aem: '12,0107',
		density: '3,51',
		melting: '3550',
		boiling: '4827',
		opening: '1787',
		discoverer: 'неизвестен',
		families: '#a0ffa0',
		focus: false,
	},
	{
		id: 7,
		period: '2',
		group: '15',
		symbol: 'N',
		name: 'Азот',
		latname: 'Nitrogenium',
		aem: '14,0067',
		density: '1,17',
		melting: '-209,9',
		boiling: '-195,8',
		opening: '1772',
		discoverer: 'Резерфорд',
		families: '#a0ffa0',
		focus: false,
	},
	{
		id: 8,
		period: '2',
		group: '16',
		symbol: 'O',
		name: 'Кислород',
		latname: 'Oxygenium',
		aem: '15,9994',
		density: '1,33',
		melting: '-218,4',
		boiling: '-182,9',
		opening: '1774',
		discoverer: 'Пристли и Шееле',
		families: '#a0ffa0',
		focus: false,
	},
	{
		id: 9,
		period: '2',
		group: '17',
		symbol: 'F',
		name: 'Фтор',
		latname: 'Fluorum',
		aem: '18,9984032',
		density: '1,58',
		melting: '-219,6',
		boiling: '-188,1',
		opening: '1886',
		discoverer: 'Муассан',
		families: '#ff9',
		focus: false,
	},
	{
		id: 10,
		period: '2',
		group: '18',
		symbol: 'Ne',
		name: 'Неон',
		latname: 'Neon',
		aem: '20,1797',
		density: '0,84',
		melting: '-248,7',
		boiling: '-246,1',
		opening: '1898',
		discoverer: 'Рамзай и Траверс',
		families: '#c0ffff',
		focus: false,
	},
	{
		id: 11,
		period: '3',
		group: '1',
		symbol: 'Na',
		name: '	Натрий',
		latname: 'Natrium',
		aem: '22,98976928',
		density: '0,97',
		melting: '97,8',
		boiling: '892',
		opening: '1807',
		discoverer: 'Дэви',
		families: '#f66',
		focus: false,
	},
	{
		id: 12,
		period: '3',
		group: '2',
		symbol: 'Mg',
		name: 'Магний',
		latname: 'Magnesium',
		aem: '24,3050',
		density: '1,74',
		melting: '648,8',
		boiling: '1107',
		opening: '1808',
		discoverer: 'Дэви',
		families: '#ffdead',
		focus: false,
	},
	{
		id: 13,
		period: '3',
		group: '13',
		symbol: 'Al',
		name: 'Алюминий',
		latname: 'Aluminium',
		aem: '26,9815386',
		density: '2,70',
		melting: '660,5',
		boiling: '2467',
		opening: '1825',
		discoverer: 'Эрстед',
		families: '#ccc',
		focus: false,
	},
	{
		id: 14,
		period: '3',
		group: '14',
		symbol: 'Si',
		name: 'Кремний',
		latname: 'Silicium',
		aem: '28,0855',
		density: '2,33',
		melting: '1410',
		boiling: '2355',
		opening: '1824',
		discoverer: 'Берцелиус',
		families: '#cc9',
		focus: false,
	},
	{
		id: 15,
		period: '3',
		group: '15',
		symbol: 'P',
		name: 'Фосфор',
		latname: 'Phosphorus',
		aem: '30,973762',
		density: '1,82',
		melting: '44',
		boiling: '280',
		opening: '1669',
		discoverer: 'Бранд',
		families: '#a0ffa0',
		focus: false,
	},
	{
		id: 16,
		period: '3',
		group: '16',
		symbol: 'S',
		name: 'Сера',
		latname: 'Sulfur, Sulphur',
		aem: '32,065',
		density: '2,06',
		melting: '113',
		boiling: '444,7',
		opening: 'доисторический период',
		discoverer: 'неизвестен',
		families: '#a0ffa0',
		focus: false,
	},
	{
		id: 17,
		period: '3',
		group: '17',
		symbol: 'Cl',
		name: 'Хлор',
		latname: 'Chlorum',
		aem: '35,453',
		density: '2,95',
		melting: '-101',
		boiling: '-34,6',
		opening: '1774',
		discoverer: 'Шееле',
		families: '#ff9',
		focus: false,
	},
	{
		id: 18,
		period: '3',
		group: '18',
		symbol: 'Ar',
		name: 'Аргон',
		latname: 'Argon',
		aem: '39,948',
		density: '1,66',
		melting: '-189,4',
		boiling: '-185,9',
		opening: '1894',
		discoverer: 'Рамзай и Рэлей',
		families: '#c0ffff',
		focus: false,
	},
	{
		id: 19,
		period: '4',
		group: '1',
		symbol: 'K',
		name: 'Калий',
		latname: 'Kalium, Calium',
		aem: '39,0983',
		density: '0,86',
		melting: '63,7',
		boiling: '774',
		opening: '1807',
		discoverer: 'Дэви',
		families: '#f66',
		focus: false,
	},
	{
		id: 20,
		period: '4',
		group: '2',
		symbol: 'Ca',
		name: 'Кальций',
		latname: 'Calcium',
		aem: '40,078',
		density: '1,54',
		melting: '839',
		boiling: '1487',
		opening: '1808',
		discoverer: 'Дэви',
		families: '#ffdead',
		focus: false,
	},
	{
		id: 21,
		period: '4',
		group: '3',
		symbol: 'Sc',
		name: 'Скандий',
		latname: 'Scandium',
		aem: '44,955912',
		density: '2,99',
		melting: '1539',
		boiling: '2832',
		opening: '1879',
		discoverer: 'Нильсон',
		families: '#ffc0c0',
		focus: false,
	},
	{
		id: 22,
		period: '4',
		group: '4',
		symbol: 'Ti	',
		name: 'Титан',
		latname: 'Titanium',
		aem: '47,867',
		density: '4,51',
		melting: '1660',
		boiling: '3260',
		opening: '1791',
		discoverer: 'Грегор и Клапрот',
		families: '#ffc0c0',
		focus: false,
	},
	{
		id: 23,
		period: '4',
		group: '5',
		symbol: 'V',
		name: 'Ванадий',
		latname: 'Vanadium',
		aem: '50,9415',
		density: '6,09',
		melting: '1890',
		boiling: '3380',
		opening: '1801',
		discoverer: 'дель Рио',
		families: '#ffc0c0',
		focus: false,
	},
	{
		id: 24,
		period: '4',
		group: '6,',
		symbol: 'Cr',
		name: 'Хром',
		latname: 'Chromium',
		aem: '51,9961',
		density: '7,14',
		melting: '1857',
		boiling: '2482',
		opening: '1797',
		discoverer: 'Воклен',
		families: '#ffc0c0',
		focus: false,
	},
	{
		id: 25,
		period: '4',
		group: '7',
		symbol: 'Mn',
		name: 'Марганец',
		latname: 'Manganum, Manganesium',
		aem: '54,938045',
		density: '7,44',
		melting: '1244',
		boiling: '2097',
		opening: '1774',
		discoverer: 'Ган',
		families: '#ffc0c0',
		focus: false,
	},
	{
		id: 26,
		period: '4',
		group: '8',
		symbol: 'Fe',
		name: 'Железо',
		latname: 'Ferrum',
		aem: '55,845',
		density: '7,87',
		melting: '1535',
		boiling: '2750',
		opening: 'доисторический период',
		discoverer: 'неизвестен',
		families: '#ffc0c0',
		focus: false,
	},
	{
		id: 27,
		period: '4',
		group: '9',
		symbol: 'Co',
		name: 'Кобальт',
		latname: 'Cobaltum',
		aem: '58,933195',
		density: '8,89',
		melting: '1495',
		boiling: '2870',
		opening: '1735',
		discoverer: 'Брандт',
		families: '#ffc0c0',
		focus: false,
	},
	{
		id: 28,
		period: '4',
		group: '10',
		symbol: 'Ni',
		name: 'Никель',
		latname: 'Niccolum',
		aem: '58,6934',
		density: '8,91',
		melting: '1453',
		boiling: '2732',
		opening: '1751',
		discoverer: 'Кронштедт',
		families: '#ffc0c0',
		focus: false,
	},
	{
		id: 29,
		period: '4',
		group: '11',
		symbol: 'Cu',
		name: 'Медь',
		latname: 'Cuprum',
		aem: '63,546',
		density: '8,92',
		melting: '1083,5',
		boiling: '2595',
		opening: 'доисторический период',
		discoverer: 'неизвестен',
		families: '#ffc0c0',
		focus: false,
	},
	{
		id: 30,
		period: '4',
		group: '12',
		symbol: 'Zn',
		name: 'Цинк',
		latname: 'Zincum',
		aem: '65,409',
		density: '7,14',
		melting: '419,6',
		boiling: '907',
		opening: 'доисторический период',
		discoverer: 'неизвестен',
		families: '#ffc0c0',
		focus: false,
	},
	{
		id: 31,
		period: '4',
		group: '13',
		symbol: 'Ga',
		name: 'Галлий',
		latname: 'Gallium',
		aem: '69,723',
		density: '5,91',
		melting: '29,8',
		boiling: '2403',
		opening: '1875',
		discoverer: 'де Буабодран',
		families: '#ccc',
		focus: false,
	},
	{
		id: 32,
		period: '4',
		group: '14',
		symbol: 'Ge',
		name: 'Германий',
		latname: 'Germanium',
		aem: '72,64',
		density: '5,32',
		melting: '937,4',
		boiling: '2830',
		opening: '1886',
		discoverer: 'Винклер',
		families: '#cc9',
		focus: false,
	},
	{
		id: 33,
		period: '4',
		group: '15',
		symbol: 'As',
		name: 'Мышьяк',
		latname: 'Arsenicum',
		aem: '74,92160',
		density: '5,72',
		melting: '613',
		boiling: '613',
		opening: '~1250',
		discoverer: 'Альберт Великий',
		families: '#cc9',
		focus: false,
	},
	{
		id: 34,
		period: '4',
		group: '16',
		symbol: 'Se',
		name: 'Селен',
		latname: 'Selenium',
		aem: '78,96',
		density: '4,82',
		melting: '217',
		boiling: '685',
		opening: '1817',
		discoverer: 'Берцелиус',
		families: '#a0ffa0',
		focus: false,
	},
	{
		id: 35,
		position: 71,
		period: '4',
		group: '17',
		symbol: 'Br',
		name: 'Бром',
		latname: 'Bromum',
		aem: '79,904',
		density: '3,14',
		melting: '-7,3',
		boiling: '58,8',
		opening: '1826',
		discoverer: 'Балар',
		families: '#ff9',
		focus: false,
	},
	{
		id: 36,
		position: 72,
		period: '4',
		group: '18',
		symbol: 'Kr',
		name: 'Криптон',
		latname: 'Krypton, Crypton',
		aem: '83,798',
		density: '3,48',
		melting: '-156,6',
		boiling: '-152,3',
		opening: '1898',
		discoverer: 'Рамзай и Траверс',
		families: '#c0ffff',
		focus: false,
	},
	{
		id: 37,
		position: 73,
		period: '5',
		group: '1',
		symbol: 'Rb',
		name: 'Рубидий',
		latname: 'Rubidium',
		aem: '85,4678',
		density: '1,53',
		melting: '39',
		boiling: '688',
		opening: '1861',
		discoverer: 'Бунзен и Кирхгоф',
		families: '#f66',
		focus: false,
	},
	{
		id: 38,
		position: 74,
		period: '5',
		group: '2',
		symbol: 'Sr',
		name: 'Стронций',
		latname: 'Strontium',
		aem: '87,62',
		density: '2,63',
		melting: '769',
		boiling: '1384',
		opening: '1790',
		discoverer: 'Кроуфорд',
		families: '#ffdead',
		focus: false,
	},
	{
		id: 39,
		position: 75,
		period: '5',
		group: '3',
		symbol: 'Y',
		name: 'Иттрий',
		latname: 'Yttrium',
		aem: '88,90585',
		density: '4,47',
		melting: '1523',
		boiling: '3337',
		opening: '1794',
		discoverer: 'Гадолин',
		families: '#ffc0c0',
		focus: false,
	},
	{
		id: 40,
		position: 76,
		period: '5',
		group: '4',
		symbol: 'Zr',
		name: 'Цирконий',
		latname: 'Zirconium',
		aem: '91,224',
		density: '6,51',
		melting: '1852',
		boiling: '4377',
		opening: '1789',
		discoverer: 'Клапрот',
		families: '#ffc0c0',
		focus: false,
	},
	{
		id: 41,
		position: 77,
		period: '5',
		group: '5',
		symbol: 'Nb',
		name: 'Ниобий',
		latname: 'Niobium',
		aem: '92,90638',
		density: '8,58',
		melting: '2468',
		boiling: '4927',
		opening: '1801',
		discoverer: 'Хэтчетт',
		families: '#ffc0c0',
		focus: false,
	},
	{
		id: 42,
		position: 78,
		period: '5',
		group: '6',
		symbol: 'Mo',
		name: 'Молибден',
		latname: 'Molybdaenum',
		aem: '95,94',
		density: '10,28',
		melting: '2617',
		boiling: '5560',
		opening: '1778',
		discoverer: 'Шееле',
		families: '#ffc0c0',
		focus: false,
	},
	{
		id: 43,
		position: 79,
		period: '5',
		group: '7',
		symbol: 'Tc',
		name: 'Технеций',
		latname: 'Technetium',
		aem: '[98,9063]',
		density: '11,49',
		melting: '2172',
		boiling: '5030',
		opening: '1937',
		discoverer: 'Перрье и Сегре',
		families: '#ffc0c0',
		focus: false,
	},
	{
		id: 44,
		position: 80,
		period: '5',
		group: '8',
		symbol: 'Ru',
		name: 'Рутений',
		latname: 'Ruthenium',
		aem: '101,07',
		density: '12,45',
		melting: '2310',
		boiling: '3900',
		opening: '1844',
		discoverer: 'Клаус',
		families: '#ffc0c0',
		focus: false,
	},
	{
		id: 45,
		position: 81,
		period: '5',
		group: '9',
		symbol: 'Rh',
		name: 'Родий',
		latname: 'Rhodium',
		aem: '102,90550',
		density: '12,41',
		melting: '1966',
		boiling: '3727',
		opening: '1803',
		discoverer: 'Волластон',
		families: '#ffc0c0',
		focus: false,
	},
	{
		id: 46,
		position: 82,
		period: '5',
		group: '10',
		symbol: 'Pd',
		name: 'Палладий',
		latname: 'Palladium',
		aem: '106,42',
		density: '12,02',
		melting: '1552',
		boiling: '3140',
		opening: '1803',
		discoverer: 'Волластон',
		families: '#ffc0c0',
		focus: false,
	},
	{
		id: 47,
		position: 83,
		period: '5',
		group: '11',
		symbol: 'Ag',
		name: 'Серебро',
		latname: 'Argentum',
		aem: '107,8682',
		density: '10,49',
		melting: '961,9',
		boiling: '2212',
		opening: 'доисторический период',
		discoverer: 'неизвестен',
		families: '#ffc0c0',
		focus: false,
	},
	{
		id: 48,
		position: 84,
		period: '5',
		group: '12',
		symbol: 'Cd',
		name: 'Кадмий',
		latname: 'Cadmium',
		aem: '112,411',
		density: '8,64',
		melting: '321',
		boiling: '765',
		opening: '1817',
		discoverer: 'Штромейер',
		families: '#ffc0c0',
		focus: false,
	},
	{
		id: 49,
		position: 85,
		period: '5',
		group: '13',
		symbol: 'In',
		name: 'Индий',
		latname: 'Indium',
		aem: '114,818',
		density: '7,31',
		melting: '156,2',
		boiling: '2080',
		opening: '1863',
		discoverer: 'Райх и Рихтер',
		families: '#ccc',
		focus: false,
	},
	{
		id: 50,
		position: 86,
		period: '5',
		group: '14',
		symbol: 'Sn',
		name: 'Олово',
		latname: 'Stannum',
		aem: '118,710',
		density: '7,29',
		melting: '232',
		boiling: '2270',
		opening: 'доисторический период',
		discoverer: 'неизвестен',
		families: '#ccc',
		focus: false,
	},
	{
		id: 51,
		position: 87,
		period: '5',
		group: '15',
		symbol: 'Sb',
		name: 'Сурьма',
		latname: 'Stibium',
		aem: '121,760',
		density: '6,69',
		melting: '630,7',
		boiling: '1750',
		opening: 'доисторический период',
		discoverer: 'неизвестен',
		families: '#cc9',
		focus: false,
	},
	{
		id: 52,
		position: 88,
		period: '5',
		group: '16',
		symbol: 'Te',
		name: 'Теллур',
		latname: 'Tellurium',
		aem: '127,60',
		density: '6,25',
		melting: '449,6',
		boiling: '990',
		opening: '1782',
		discoverer: 'Франц Йозеф Мюллер',
		families: '#cc9',
		focus: false,
	},
	{
		id: 53,
		position: 89,
		period: '5',
		group: '17',
		symbol: 'I',
		name: 'Йод',
		latname: 'Iodium, Jodium',
		aem: '126,90447',
		density: '4,94',
		melting: '113,5',
		boiling: '184,4',
		opening: '1811',
		discoverer: 'Куртуа',
		families: '#ff9',
		focus: false,
	},
	{
		id: 54,
		position: 90,
		period: '5',
		group: '18',
		symbol: 'Xe',
		name: 'Ксенон',
		latname: 'Xenon',
		aem: '131,293',
		density: '4,49',
		melting: '-111,9',
		boiling: '-107',
		opening: '1898',
		discoverer: 'Рамзай и Траверс',
		families: '#c0ffff',
		focus: false,
	},
	{
		id: 55,
		position: 91,
		period: '6',
		group: '1',
		symbol: 'Cs',
		name: 'Цезий',
		latname: 'Caesium',
		aem: '132,9054519',
		density: '1,90',
		melting: '28,4',
		boiling: '690',
		opening: '1860',
		discoverer: 'Бунзен и Кирхгоф',
		families: '#f66',
		focus: false,
	},
	{
		id: 56,
		position: 92,
		period: '6',
		group: '2',
		symbol: 'Ba',
		name: 'Барий',
		latname: 'Barium',
		aem: '137,327',
		density: '3,65',
		melting: '725',
		boiling: '1640',
		opening: '1808',
		discoverer: 'Дэви',
		families: '#ffdead',
		focus: false,
	},
	{
		id: 57,
		period: '6',
		group: '0',
		symbol: 'La',
		name: 'Лантан',
		latname: 'Lanthanum',
		aem: '138,90547',
		density: '6,16',
		melting: '920',
		boiling: '3454',
		opening: '1839',
		discoverer: 'Мосандер',
		families: '#ffc0c0',
		focus: false,
	},
	{
		id: 58,
		period: '6',
		group: '0',
		symbol: 'Ce',
		name: 'Церий',
		latname: 'Cerium',
		aem: '140,116',
		density: '6,77',
		melting: '798',
		boiling: '3257',
		opening: '1803',
		discoverer: 'фон Хисингер и Берцелиус',
		families: '#ffbfff',
		focus: false,
	},
	{
		id: 59,
		period: '6',
		group: '0',
		symbol: 'Pr',
		name: 'Празеодим',
		latname: 'Praseodymium',
		aem: '140,90765',
		density: '6,48',
		melting: '931',
		boiling: '3212',
		opening: '1895',
		discoverer: 'Ауэр фон Вельсбах',
		families: '#ffbfff',
		focus: false,
	},
	{
		id: 60,
		period: '6',
		group: '0',
		symbol: 'Nd',
		name: 'Неодим',
		latname: 'Neodymium',
		aem: '144,242',
		density: '7,00',
		melting: '1010',
		boiling: '3127',
		opening: '1895',
		discoverer: 'Ауэр фон Вельсбах',
		families: '#ffbfff',
		focus: false,
	},
	{
		id: 61,
		period: '6',
		group: '0',
		symbol: 'Pm',
		name: 'Прометий',
		latname: 'Promethium',
		aem: '[146,9151]',
		density: '7,22',
		melting: '1080',
		boiling: '2730',
		opening: '1945',
		discoverer: 'Маринский и Гленденин',
		families: '#ffbfff',
		focus: false,
	},
	{
		id: 62,
		period: '6',
		group: '0',
		symbol: 'Sm',
		name: 'Самарий',
		latname: 'Samarium',
		aem: '150,36',
		density: '7,54',
		melting: '1072',
		boiling: '1778',
		opening: '1879',
		discoverer: 'де Буабодран',
		families: '#ffbfff',
		focus: false,
	},
	{
		id: 63,
		period: '6',
		group: '0',
		symbol: 'Eu',
		name: 'Европий',
		latname: 'Europium',
		aem: '151,964',
		density: '5,25',
		melting: '822',
		boiling: '1597',
		opening: '1901',
		discoverer: 'Демарсе',
		families: '#ffbfff',
		focus: false,
	},
	{
		id: 64,
		period: '6',
		group: '0',
		symbol: 'Gd',
		name: 'Гадолиний',
		latname: 'Gadolinium',
		aem: '157,25',
		density: '7,89',
		melting: '1311',
		boiling: '3233',
		opening: '1880',
		discoverer: 'де Мариньяк',
		families: '#ffbfff',
		focus: false,
	},
	{
		id: 65,
		period: '6',
		group: '0',
		symbol: 'Tb',
		name: 'Тербий',
		latname: 'Terbium',
		aem: '158,92535',
		density: '8,25',
		melting: '1360',
		boiling: '3041',
		opening: '1843',
		discoverer: 'Мосандер',
		families: '#ffbfff',
		focus: false,
	},
	{
		id: 66,
		period: '6',
		group: '0',
		symbol: 'Dy',
		name: 'Диспрозий',
		latname: 'Dysprosium',
		aem: '162,500',
		density: '8,56',
		melting: '1409',
		boiling: '2335',
		opening: '1886',
		discoverer: 'де Буабодран',
		families: '#ffbfff',
		focus: false,
	},
	{
		id: 67,
		period: '6',
		group: '0',
		symbol: 'Ho',
		name: 'Гольмий',
		latname: 'Holmium',
		aem: '164,93032',
		density: '8,78',
		melting: '1470',
		boiling: '2720',
		opening: '1878',
		discoverer: 'Соре',
		families: '#ffbfff',
		focus: false,
	},
	{
		id: 68,
		period: '6',
		group: '0',
		symbol: 'Er',
		name: 'Эрбий',
		latname: 'Erbium',
		aem: '167,259',
		density: '9,05',
		melting: '1522',
		boiling: '2510',
		opening: '1842',
		discoverer: 'Мосандер',
		families: '#ffbfff',
		focus: false,
	},
	{
		id: 69,
		period: '6',
		group: '0',
		symbol: 'Tm',
		name: 'Тулий',
		latname: 'Thulium',
		aem: '168,93421',
		density: '9,32',
		melting: '1545',
		boiling: '1727',
		opening: '1879',
		discoverer: 'Клеве',
		families: '#ffbfff',
		focus: false,
	},
	{
		id: 70,
		period: '6',
		group: '0',
		symbol: 'Yb',
		name: 'Иттербий',
		latname: 'Ytterbium',
		aem: '173,04',
		density: '6,97',
		melting: '824',
		boiling: '1193',
		opening: '1878',
		discoverer: 'де Мариньяк',
		families: '#ffbfff',
		focus: false,
	},
	{
		id: 71,
		period: '6',
		group: '3',
		symbol: 'Lu',
		name: 'Лютеций',
		latname: 'Lutetium',
		aem: '174,967',
		density: '9,84',
		melting: '1656',
		boiling: '3315',
		opening: '1907',
		discoverer: 'Урбэн',
		families: '#ffbfff',
		focus: false,
	},
	{
		id: 72,
		position: 94,
		period: '6',
		group: '4',
		symbol: 'Hf',
		name: 'Гафний',
		latname: 'Hafnium',
		aem: '178,49',
		density: '13,31',
		melting: '2150',
		boiling: '5400',
		opening: '1923',
		discoverer: 'Костер и де Хевеши',
		families: '#ffc0c0',
		focus: false,
	},
	{
		id: 73,
		position: 95,
		period: '6',
		group: '5',
		symbol: 'Ta',
		name: 'Тантал',
		latname: 'Tantalum',
		aem: '180,9479',
		density: '16,68',
		melting: '2996',
		boiling: '5425',
		opening: '1802',
		discoverer: 'Экеберг',
		families: '#ffc0c0',
		focus: false,
	},
	{
		id: 74,
		position: 96,
		period: '6',
		group: '6',
		symbol: 'W',
		name: 'Вольфрам',
		latname: 'Wolframium',
		aem: '183,84',
		density: '19,26',
		melting: '3407',
		boiling: '5927',
		opening: '1783',
		discoverer: 'Элюяр',
		families: '#ffc0c0',
		focus: false,
	},
	{
		id: 75,
		position: 97,
		period: '6',
		group: '7',
		symbol: 'Re',
		name: 'Рений',
		latname: 'Rhenium',
		aem: '186,207',
		density: '21,03',
		melting: '3180',
		boiling: '5873',
		opening: '1925',
		discoverer: 'Ноддак, Такке и Берг',
		families: '#ffc0c0',
		focus: false,
	},
	{
		id: 76,
		position: 98,
		period: '6',
		group: '8',
		symbol: 'Os',
		name: 'Осмий',
		latname: 'Osmium',
		aem: '190,23',
		density: '22,61',
		melting: '3045',
		boiling: '5027',
		opening: '1803',
		discoverer: 'Теннант',
		families: '#ffc0c0',
		focus: false,
	},
	{
		id: 77,
		position: 99,
		period: '6',
		group: '9',
		symbol: 'Ir',
		name: 'Иридий',
		latname: 'Iridium',
		aem: '192,217',
		density: '22,65',
		melting: '2410',
		boiling: '4130',
		opening: '1803',
		discoverer: 'Теннант',
		families: '#ffc0c0',
		focus: false,
	},
	{
		id: 78,
		position: 100,
		period: '6',
		group: '10',
		symbol: 'Pt',
		name: 'Платина',
		latname: 'Platinum',
		aem: '195,084',
		density: '21,45',
		melting: '1772',
		boiling: '3827',
		opening: '1557',
		discoverer: 'Скалигер',
		families: '#ffc0c0',
		focus: false,
	},
	{
		id: 79,
		position: 101,
		period: '6',
		group: '11',
		symbol: 'Au',
		name: 'Золото',
		latname: 'Aurum',
		aem: '196,966569',
		density: '19,32',
		melting: '1064,4',
		boiling: '2940',
		opening: 'доисторический период',
		discoverer: 'неизвестен',
		families: '#ffc0c0',
		focus: false,
	},
	{
		id: 80,
		position: 102,
		period: '6',
		group: '12',
		symbol: 'Hg',
		name: 'Ртуть',
		latname: 'Hydrargyrum',
		aem: '200,59',
		density: '13,55',
		melting: '-38,9',
		boiling: '356,6',
		opening: 'доисторический период',
		discoverer: 'неизвестен',
		families: '#ffc0c0',
		focus: false,
	},
	{
		id: 81,
		position: 103,
		period: '6',
		group: '13',
		symbol: 'Tl',
		name: 'Таллий',
		latname: 'Thallium',
		aem: '204,3833',
		density: '11,85',
		melting: '303,6',
		boiling: '1457',
		opening: '1861',
		discoverer: 'Крукс',
		families: '#ccc',
		focus: false,
	},
	{
		id: 82,
		position: 104,
		period: '6',
		group: '14',
		symbol: 'Pb',
		name: 'Свинец',
		latname: 'Plumbum',
		aem: '207,2',
		density: '11,34',
		melting: '327,5',
		boiling: '1740',
		opening: 'доисторический период',
		discoverer: 'неизвестен',
		families: '#ccc',
		focus: false,
	},
	{
		id: 83,
		position: 105,
		period: '6',
		group: '15',
		symbol: 'Bi',
		name: 'Висмут',
		latname: 'Bismuthum',
		aem: '208,98040',
		density: '9,80',
		melting: '271,4',
		boiling: '1560',
		opening: '1753',
		discoverer: 'Жоффруа',
		families: '#ccc',
		focus: false,
	},
	{
		id: 84,
		position: 106,
		period: '6',
		group: '16',
		symbol: 'Po',
		name: 'Полоний',
		latname: 'Polonium',
		aem: '[208,9824]',
		density: '9,20',
		melting: '254',
		boiling: '962',
		opening: '1898',
		discoverer: 'Мария и Пьер Кюри',
		families: '#cc9',
		focus: false,
	},
	{
		id: 85,
		position: 107,
		period: '6',
		group: '17',
		symbol: 'At',
		name: 'Астат',
		latname: 'Astatum',
		aem: '[209,9871]',
		density: '[5]',
		melting: '302',
		boiling: '337',
		opening: '1940',
		discoverer: 'Д. Р. Корсон, К. Р. Маккензи и Э. Сегре',
		families: '#ff9',
		focus: false,
	},
	{
		id: 86,
		position: 108,
		period: '6',
		group: '18',
		symbol: 'Rn',
		name: 'Радон',
		latname: 'Radon',
		aem: '[222,0176]',
		density: '9,23',
		melting: '-71',
		boiling: '-61,8',
		opening: '1900',
		discoverer: 'Дорн',
		families: '#c0ffff',
		focus: false,
	},
	{
		id: 87,
		position: 109,
		period: '7',
		group: '1',
		symbol: 'Fr',
		name: 'Франций',
		latname: 'Francium',
		aem: '[223,0197]',
		density: '1,87',
		melting: '27',
		boiling: '677',
		opening: '1939',
		discoverer: 'Перей',
		families: '#f66',
		focus: false,
	},
	{
		id: 88,
		position: 110,
		period: '7',
		group: '2',
		symbol: 'Ra',
		name: 'Радий',
		latname: 'Radium',
		aem: '[226,0254]',
		density: '5,50',
		melting: '700',
		boiling: '1140',
		opening: '1898',
		discoverer: 'Мария и Пьер Кюри',
		families: '#ffdead',
		focus: false,
	},
	{
		id: 89,
		period: '7',
		group: '0',
		symbol: 'Ac',
		name: 'Актиний',
		latname: 'Actinium',
		aem: '[227,0278]',
		density: '10,07',
		melting: '1047',
		boiling: '3197',
		opening: '1899',
		discoverer: 'Дебьерн',
		families: '#ffc0c0',
		focus: false,
	},
	{
		id: 90,
		period: '7',
		group: '0',
		symbol: 'Th',
		name: 'Торий',
		latname: 'Thorium',
		aem: '232,03806',
		density: '11,72',
		melting: '1750',
		boiling: '4787',
		opening: '1829',
		discoverer: 'Берцелиус',
		families: '#ef99cc',
		focus: false,
	},
	{
		id: 91,
		period: '7',
		group: '0',
		symbol: 'Pa',
		name: 'Протактиний',
		latname: 'Protactinium',
		aem: '231,03588',
		density: '15,37',
		melting: '1554',
		boiling: '4030',
		opening: '1917',
		discoverer: 'Содди, Кранстон и Ган',
		families: '#ef99cc',
		focus: false,
	},
	{
		id: 92,
		period: '7',
		group: '0',
		symbol: 'U',
		name: 'Уран',
		latname: 'Uranium',
		aem: '238,02891',
		density: '18,97',
		melting: '1132,4',
		boiling: '3818',
		opening: '1789',
		discoverer: 'Клапрот',
		families: '#ef99cc',
		focus: false,
	},
	{
		id: 93,
		period: '7',
		group: '0',
		symbol: 'Np',
		name: 'Нептуний',
		latname: 'Neptunium',
		aem: '[237,0482]',
		density: '20,48',
		melting: '640',
		boiling: '3902',
		opening: '1940',
		discoverer: 'Макмиллан и Абелсон',
		families: '#ef99cc',
		focus: false,
	},
	{
		id: 94,
		period: '7',
		group: '0',
		symbol: 'Pu',
		name: 'Плутоний',
		latname: 'Plutonium',
		aem: '[244,0642]',
		density: '19,74',
		melting: '641',
		boiling: '3327',
		opening: '1940',
		discoverer: 'Сиборг',
		families: '#ef99cc',
		focus: false,
	},
	{
		id: 95,
		period: '7',
		group: '0',
		symbol: 'Am',
		name: 'Америций',
		latname: 'Americium',
		aem: '[243,0614]',
		density: '13,67',
		melting: '994',
		boiling: '2607',
		opening: '1944',
		discoverer: 'Сиборг',
		families: '#ef99cc',
		focus: false,
	},
	{
		id: 96,
		period: '7',
		group: '0',
		symbol: 'Cm',
		name: 'Кюрий',
		latname: 'Curium',
		aem: '[247,0703]',
		density: '13,51',
		melting: '1340',
		opening: '1944',
		discoverer: 'Сиборг',
		families: '#ef99cc',
		focus: false,
	},
	{
		id: 97,
		period: '7',
		group: '0',
		symbol: 'Bk',
		name: 'Берклий',
		latname: 'Berkelium',
		aem: '[247,0703]',
		density: '13,25',
		melting: '986',
		opening: '1949',
		discoverer: 'Сиборг',
		families: '#ef99cc',
		focus: false,
	},
	{
		id: 98,
		period: '7',
		group: '0',
		symbol: 'Cf',
		name: 'Калифорний',
		latname: 'Californium',
		aem: '[251,0796]',
		density: '15,1',
		melting: '900',
		opening: '1950',
		discoverer: 'Сиборг',
		families: '#ef99cc',
		focus: false,
	},
	{
		id: 99,
		period: '7',
		group: '0',
		symbol: 'Es',
		name: 'Эйнштейний',
		latname: 'Einsteinium',
		aem: '[252,0829]',
		density: '13,5',
		melting: '860',
		opening: '1952',
		discoverer: 'Сиборг',
		families: '#ef99cc',
		focus: false,
	},
	{
		id: 100,
		period: '7',
		group: '0',
		symbol: 'Fm',
		name: 'Фермий',
		latname: 'Fermium',
		aem: '[257,0951]',
		opening: '1952',
		discoverer: 'Сиборг',
		families: '#ef99cc',
		focus: false,
	},
	{
		id: 101,
		period: '7',
		group: '0',
		symbol: 'Md',
		name: 'Менделевий',
		latname: 'Mendelevium,Mendeleevium',
		aem: '[258,0986]',
		opening: '1955',
		discoverer: 'Сиборг',
		families: '#ef99cc',
		focus: false,
	},
	{
		id: 102,
		period: '7',
		group: '0',
		symbol: 'No',
		name: 'Нобелий',
		latname: 'Nobelium',
		aem: '[259,1009]',
		opening: '1965',
		discoverer: 'Флёров',
		families: '#ef99cc',
		focus: false,
	},
	{
		id: 103,
		period: '7',
		group: '3',
		symbol: 'Lr',
		name: 'Лоуренсий',
		latname: 'Lawrencium, Launtium',
		aem: '[266]',
		opening: '1961',
		discoverer: 'Гиорсо',
		families: '#ef99cc',
		focus: false,
	},
	{
		id: 104,
		position: 112,
		period: '7',
		group: '4',
		symbol: 'Rf',
		name: 'Резерфордий',
		latname: 'Rutherfordium',
		aem: '[267]',
		density: '23',
		opening: '1964/69',
		discoverer: 'Флёров',
		families: '#ffc0c0',
		focus: false,
	},
	{
		id: 105,
		position: 113,
		period: '7',
		group: '5',
		symbol: 'Db',
		name: 'Дубний',
		latname: 'Dubnium',
		aem: '[268]',
		density: '29',
		opening: '1967/70',
		discoverer: 'Флёров',
		families: '#ffc0c0',
		focus: false,
	},
	{
		id: 106,
		position: 114,
		period: '7',
		group: '6',
		symbol: 'Sg',
		name: 'Сиборгий',
		latname: 'Seaborgium',
		aem: '[269]',
		density: '35',
		opening: '1974',
		discoverer: 'Флёров',
		families: '#ffc0c0',
		focus: false,
	},
	{
		id: 107,
		position: 115,
		period: '7',
		group: '7',
		symbol: 'Bh',
		name: 'Борий',
		latname: 'Bohrium',
		aem: '[270]',
		density: '37',
		opening: '1976',
		discoverer: 'Оганесян',
		families: '#ffc0c0',
		focus: false,
	},
	{
		id: 108,
		position: 116,
		period: '7',
		group: '8',
		symbol: 'Hs',
		name: 'Хассий',
		latname: 'Hassium',
		aem: '[277]',
		opening: '1984',
		discoverer: 'GSI',
		families: '#ffc0c0',
		focus: false,
	},
	{
		id: 109,
		position: 117,
		period: '7',
		group: '9',
		symbol: 'Mt',
		name: 'Мейтнерий',
		latname: 'Meitnerium',
		aem: '[278]',
		density: '37,4',
		opening: '1982',
		discoverer: 'GSI',
		families: '#ffc0c0',
		focus: false,
	},
	{
		id: 110,
		position: 118,
		period: '7',
		group: '10',
		symbol: 'Ds',
		name: 'Дармштадтий',
		latname: 'Darmstadtium',
		aem: '[281]',
		opening: '1994',
		discoverer: 'GSI',
		families: '#ffc0c0',
		focus: false,
	},
	{
		id: 111,
		position: 119,
		period: '7',
		group: '11',
		symbol: 'Rg',
		name: 'Рентгений',
		latname: 'Roentgenium',
		aem: '[282]',
		opening: '1994',
		discoverer: 'GSI',
		families: '#ffc0c0',
		focus: false,
	},
	{
		id: 112,
		position: 120,
		period: '7',
		group: '12',
		symbol: 'Cn',
		name: 'Коперниций',
		latname: 'Copernicium',
		aem: '[285]',
		opening: '1996',
		discoverer: 'GSI',
		families: '#ffc0c0',
		focus: false,
	},
	{
		id: 113,
		position: 121,
		period: '7',
		group: '13',
		symbol: 'Nh',
		name: 'Нихоний',
		latname: 'Nihonium',
		aem: '[286]',
		opening: '2004',
		discoverer: 'ОИЯИ, LLNL',
		families: '#ccc',
		focus: false,
	},
	{
		id: 114,
		position: 122,
		period: '7',
		group: '14',
		symbol: 'Fl',
		name: 'Флеровий',
		latname: 'Flerovium',
		aem: '[289]',
		opening: '1999',
		discoverer: 'ОИЯИ',
		families: '#ccc',
		focus: false,
	},
	{
		id: 115,
		position: 123,
		period: '7',
		group: '15',
		symbol: 'Mc',
		name: 'Московий',
		latname: 'Moscovium',
		aem: '[290]',
		opening: '2004',
		discoverer: 'ОИЯИ, LLNL',
		families: '#ccc',
		focus: false,
	},
	{
		id: 116,
		position: 124,
		period: '7',
		group: '16',
		symbol: 'Lv',
		name: 'Ливерморий',
		latname: 'Livermorium',
		aem: '[293]',
		opening: '2000',
		discoverer: 'ОИЯИ, LLNL',
		families: '#ccc',
		focus: false,
	},
	{
		id: 117,
		position: 125,
		period: '7',
		group: '17',
		symbol: 'Ts',
		name: 'Теннессин',
		latname: 'Tennessine',
		aem: '[294]',
		opening: '2010',
		discoverer: 'ОИЯИ',
		families: '#ff9',
		focus: false,
	},
	{
		id: 118,
		position: 126,
		period: '7',
		group: '18',
		symbol: 'Og',
		name: 'Оганесон',
		latname: 'Oganesson',
		aem: '[294]',
		opening: '2004',
		discoverer: 'ОИЯИ',
		families: '#c0ffff',
		focus: false,
	},
	{
		id: 119,
		name: 'Унуненний',
		symbol: 'Uue',
		latname: 'Ununennium',
		focus: false,
	},
	{
		id: 120,
		name: 'Унбинилий',
		symbol: 'Ubn',
		latname: 'Unbinilium',
		focus: false,
	},
	{
		id: 121,
		name: 'Унбиуний',
		symbol: 'Ubu',
		latname: 'Unbiunium',
		focus: false,
	},
	{
		id: 122,
		name: 'Унбибий',
		symbol: 'Ubb',
		latname: 'Unbibium',
		focus: false,
	},
	{
		id: 123,
		name: 'Унбитрий',
		symbol: 'Ubt',
		latname: 'Unbitrium',
		focus: false,
	},
	{
		id: 124,
		name: 'Унбиквадий',
		symbol: 'Ubq',
		latname: 'Unbiquadium',
		focus: false,
	},
	{
		id: 125,
		name: 'Унбипентий',
		symbol: 'Ubp',
		latname: 'Unbipentium',
		focus: false,
	},
	{
		id: 126,
		name: 'Унбигексий',
		symbol: 'Ubh',
		latname: 'Unbihexium',
		focus: false,
	},
	{
		id: 127,
		name: 'Унбисептий',
		symbol: 'Ubs',
		latname: 'Unbiseptium',
		focus: false,
	},
];
export default products;
